--flagfile=modules/common/data/global_flagfile.txt
--planning_upper_speed_limit=33.00
--default_cruise_speed=16.0
--ignore_overlapped_obstacle=true
--prioritize_change_lane
--nouse_multi_thread_to_add_obstacles
# --min_past_history_points_len=10
--traffic_rule_config_filename=modules/planning/planning_component/conf/traffic_rule_config.pb.txt
--min_length_for_lane_change=5.0
# --smoother_config_filename=modules/planning/planning_component/conf/qp_spline_smoother_config.pb.txt
--enable_print_curve=true
--enable_reference_line_stitching=false
--destination_check_distance=4.0
--nonstatic_obstacle_nudge_l_buffer=0.0
# --smoother_config_filename=modules/planning/planning_component/conf/spiral_smoother_config.pb.txt
--obstacle_lat_buffer=0.3
--longitudinal_jerk_upper_bound=1e9
--obstacle_lon_end_buffer_park=0.1
--passed_destination_threshold=0.3
--nouse_s_curve_speed_smooth
--smoother_config_filename=modules/planning/planning_component/conf/discrete_points_smoother_config.pb.txt
--replan_lateral_distance_threshold=1.0
--use_st_drivable_boundary=false
--passed_referenceline_end_threshold=1.5
--replan_longitudinal_distance_threshold=4.0
# --speed_bump_speed_limit=3
# --use_dual_variable_warm_start=true
# --parking_inwards=false
--enable_pull_over_at_destination=false
# --enable_parallel_hybrid_a=true
--path_bounds_decider_resolution=0.5
# --enable_record_debug=true
--enable_parallel_trajectory_smoothing
# --use_front_axe_center_in_path_planning=true
--path_bounds_horizon=150
--export_chart=true
--enable_smoother_failsafe
--trajectory_time_length=15.0
--use_iterative_anchoring_smoother
--longitudinal_jerk_lower_bound=-1e9
--reference_line_max_forward_heading_diff=3.1415