load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "bus_bay_transfer_proto",
    srcs = ["bus_bay_transfer.proto"],
)

apollo_package()