syntax = "proto2";

import "modules/planning/planning_base/proto/piecewise_jerk_path_config.proto";

package apollo.planning;

message LaneChangePathConfig {
  optional PiecewiseJerkPathConfig path_optimizer_config = 1;
  //whether to extend adc bound buffer
  optional double extend_adc_buffer = 2;
  // not allowed to change lane this amount of time if just failed
  optional double change_lane_fail_freeze_time = 3;
  // not allowed to change lane this amount of time if just finished
  optional double change_lane_success_freeze_time = 4;
  // The distance of lane-change preparation on current lane.
  optional double lane_change_prepare_length = 5;
  optional double safe_time_on_same_direction = 6 [default = 3.0];
  optional double safe_time_on_opposite_direction = 7 [default = 5.0];
  optional double forward_min_safe_distance_on_same_direction = 8
      [default = 10.0];
  optional double backward_min_safe_distance_on_same_direction = 9
      [default = 10.0];
  optional double forward_min_safe_distance_on_opposite_direction = 10
      [default = 50.0];
  optional double backward_min_safe_distance_on_opposite_direction = 11
      [default = 1.0];
  optional double lane_change_distance_buffer = 12 [default = 0.5];
  optional int32 max_speed_fallback_count = 13 [default = 1];
  optional double in_change_lane_safe_time_on_same_direction = 14
      [default = 3.0];
  optional double in_change_lane_backward_min_safe_distance_on_same_direction =
      15 [default = 10.0];
  optional bool ignore_forward_dynamic_obstacles_in_change_lane = 16
      [default = false];
}
